# Generated by Django 2.2.5 on 2019-09-10 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_remove_imagen_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='archivo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
